# Dependencies
# markdown:         redcarpetkramdown
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            It's Me
tagline:          'S(k|c)eptical Statistician'
description:      'S(k|c)eptical Statistician'
url:              http://jrnew.github.io
baseurl:          

author:
  name:           'JR New'
  url:            https://twitter.com/jrnewww

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/jrnew

# Plugins
plugins:          [jekyll-paginate, jekyll-gist]

# Disqus comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: skcepticalstatistician

# Google analytics
google_analytics: UA-42087579-3